//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiNCoreKlassifiserer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dataleveranse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dataleveranse()
        {
            this.KartlagtOmråde = new HashSet<KartlagtOmråde>();
        }
    
        public int id { get; set; }
        public int doc_id { get; set; }
        public string navn { get; set; }
        public System.DateTime leveranseDato { get; set; }
        public int operatør_id { get; set; }
        public string begrunnelseForEndring { get; set; }
        public string beskrivelse { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<System.DateTime> opprettet { get; set; }
    
        public virtual Kontakt Kontakt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KartlagtOmråde> KartlagtOmråde { get; set; }
    }
}
