//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiNCoreKlassifiserer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokument
    {
        public int id { get; set; }
        public System.Guid doc_guid { get; set; }
        public Nullable<int> kartlagtOmråde_id { get; set; }
        public Nullable<int> naturområde_id { get; set; }
        public Nullable<int> områdeKartType_id { get; set; }
        public Nullable<int> rutenettkartType_id { get; set; }
        public string tittel { get; set; }
        public string beskrivelse { get; set; }
        public Nullable<int> kartlegger_id { get; set; }
        public string filsti { get; set; }
    
        public virtual KartlagtOmråde KartlagtOmråde { get; set; }
        public virtual Kontakt Kontakt { get; set; }
        public virtual Naturområde Naturområde { get; set; }
        public virtual OmrådekartType OmrådekartType { get; set; }
        public virtual RutenettkartType RutenettkartType { get; set; }
    }
}
