//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiNCoreKlassifiserer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EgendefinertVariabel
    {
        public int id { get; set; }
        public int naturområdetype_id { get; set; }
        public string spesifikasjon { get; set; }
        public string trinn { get; set; }
        public Nullable<int> kartlegger_id { get; set; }
        public Nullable<System.Guid> localId { get; set; }
        public string tematiskId { get; set; }
    
        public virtual NaturområdeType NaturområdeType { get; set; }
    }
}
