//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiNCoreKlassifiserer
{
    using System;
    using System.Collections.Generic;
    
    public partial class KartlagtOmråde
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KartlagtOmråde()
        {
            this.Dokument = new HashSet<Dokument>();
            this.EgendefinertVariabelDefinisjon = new HashSet<EgendefinertVariabelDefinisjon>();
            this.Naturområde = new HashSet<Naturområde>();
            this.Standardvariabel = new HashSet<Standardvariabel>();
        }
    
        public int id { get; set; }
        public int dataleveranse_id { get; set; }
        public System.Guid localId { get; set; }
        public string navnerom { get; set; }
        public string versjonId { get; set; }
        public string opprinneligReferansesystem { get; set; }
        public string program { get; set; }
        public string prosjekt { get; set; }
        public string prosjektbeskrivelse { get; set; }
        public string formål { get; set; }
        public int oppdragsgiver_id { get; set; }
        public int eier_id { get; set; }
        public System.DateTime kartlagtFraDato { get; set; }
        public System.DateTime kartlagtTilDato { get; set; }
        public string kartleggingsmålestokk { get; set; }
        public string oppløsning { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geometri { get; set; }
        public string målemetode { get; set; }
        public Nullable<int> nøyaktighet { get; set; }
        public string visibility { get; set; }
        public string målemetodeHøyde { get; set; }
        public Nullable<int> nøyaktighetHøyde { get; set; }
        public Nullable<int> maksimaltAvvik { get; set; }
        public int bruksbegrensning { get; set; }
        public int totalklassifikasjonskvalitet { get; set; }
    
        public virtual Dataleveranse Dataleveranse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dokument> Dokument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EgendefinertVariabelDefinisjon> EgendefinertVariabelDefinisjon { get; set; }
        public virtual Kontakt Kontakt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Naturområde> Naturområde { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Standardvariabel> Standardvariabel { get; set; }
    }
}
