//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiNCoreKlassifiserer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NaturområdeType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NaturområdeType()
        {
            this.Beskrivelsesvariabel = new HashSet<Beskrivelsesvariabel>();
            this.EgendefinertVariabel = new HashSet<EgendefinertVariabel>();
        }
    
        public int id { get; set; }
        public int naturområde_id { get; set; }
        public string tematiskId { get; set; }
        public string kode { get; set; }
        public Nullable<int> kartlegger_id { get; set; }
        public Nullable<System.DateTime> kartlagt { get; set; }
        public double andel { get; set; }
        public int totalklassifikasjonskvalitet { get; set; }
        public Nullable<System.Guid> localId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beskrivelsesvariabel> Beskrivelsesvariabel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EgendefinertVariabel> EgendefinertVariabel { get; set; }
        public virtual Kontakt Kontakt { get; set; }
        public virtual Naturområde Naturområde { get; set; }
    }
}
