//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiNCoreKlassifiserer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Naturområde
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Naturområde()
        {
            this.Beskrivelsesvariabel = new HashSet<Beskrivelsesvariabel>();
            this.Dokument = new HashSet<Dokument>();
            this.NaturområdeType = new HashSet<NaturområdeType>();
            this.Område = new HashSet<Område>();
        }
    
        public int id { get; set; }
        public int kartlagtOmråde_id { get; set; }
        public System.Guid localId { get; set; }
        public string navnerom { get; set; }
        public string versjonId { get; set; }
        public string versjon { get; set; }
        public int naturnivå_id { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geometri { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geometriSenterpunkt { get; set; }
        public Nullable<int> kartlegger_id { get; set; }
        public Nullable<System.DateTime> kartlagt { get; set; }
        public string beskrivelse { get; set; }
        public string institusjon { get; set; }
        public int stedfestingskvalitet { get; set; }
        public string tematiskId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beskrivelsesvariabel> Beskrivelsesvariabel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dokument> Dokument { get; set; }
        public virtual KartlagtOmråde KartlagtOmråde { get; set; }
        public virtual Kontakt Kontakt { get; set; }
        public virtual Naturnivå Naturnivå { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NaturområdeType> NaturområdeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Område> Område { get; set; }
    }
}
