//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiNCoreKlassifiserer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Område
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Område()
        {
            this.Områdekart = new HashSet<Områdekart>();
            this.Naturområde = new HashSet<Naturområde>();
        }
    
        public int id { get; set; }
        public int geometriType_id { get; set; }
        public Nullable<int> nummer { get; set; }
        public string navn { get; set; }
        public string kategori { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geometri { get; set; }
    
        public virtual OmrådeType OmrådeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Områdekart> Områdekart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Naturområde> Naturområde { get; set; }
    }
}
