//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiNCoreKlassifiserer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rutenett
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rutenett()
        {
            this.Rutenettkart = new HashSet<Rutenettkart>();
        }
    
        public int id { get; set; }
        public Nullable<int> rutenettype_id { get; set; }
        public string geometrieId { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geometri { get; set; }
    
        public virtual Rutenettype Rutenettype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rutenettkart> Rutenettkart { get; set; }
    }
}
