//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiNCoreKlassifiserer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rutenettkart
    {
        public int id { get; set; }
        public int rutenettkartType_id { get; set; }
        public int rutenett_id { get; set; }
        public string trinn { get; set; }
    
        public virtual Rutenett Rutenett { get; set; }
        public virtual RutenettkartType RutenettkartType { get; set; }
    }
}
