//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiNCoreKlassifiserer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Standardvariabel
    {
        public int id { get; set; }
        public int kartlagtOmråde_id { get; set; }
        public string koderegister { get; set; }
        public string kodeversjon { get; set; }
        public string kode { get; set; }
    
        public virtual KartlagtOmråde KartlagtOmråde { get; set; }
    }
}
