//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms_dev3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Naturområde_RødlisteKlassifisering
    {
        public int Id { get; set; }
        public long naturområde_id { get; set; }
    
        public virtual RødlisteKlassifisering RødlisteKlassifisering { get; set; }
    }
}
