//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms_dev3
{
    using System;
    using System.Collections.Generic;
    
    public partial class RødlisteVurderingsenhet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RødlisteVurderingsenhet()
        {
            this.children = new HashSet<RødlisteVurderingsenhet>();
            this.parent = new HashSet<RødlisteVurderingsenhet>();
            this.RødlisteKlassifisering = new HashSet<RødlisteKlassifisering>();
            this.Kriterie = new HashSet<Kriterie>();
            this.Påvirkning = new HashSet<Påvirkning>();
        }
    
        public int Id { get; set; }
        public string verdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RødlisteVurderingsenhet> children { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RødlisteVurderingsenhet> parent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RødlisteKlassifisering> RødlisteKlassifisering { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kriterie> Kriterie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Påvirkning> Påvirkning { get; set; }
        public virtual RødlisteVurdeingsenhetVersjon RødlisteVurdeingsenhetVersjon { get; set; }
        public virtual Naturnivå Naturnivå { get; set; }
        public virtual Kategori Kategori { get; set; }
    }
}
