//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms_dev3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RødlistedeNaturtyperKlassifiseringContainer : DbContext
    {
        public RødlistedeNaturtyperKlassifiseringContainer()
            : base("name=RødlistedeNaturtyperKlassifiseringContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NaturområdeTypeKode> NaturområdeTypeKodeSet { get; set; }
        public virtual DbSet<RødlisteVurderingsenhet> RødlisteVurderingsenhetSet { get; set; }
        public virtual DbSet<KartleggingsKode> KartleggingsKodeSet { get; set; }
        public virtual DbSet<RødlisteKlassifisering> RødlisteKlassifiseringSet { get; set; }
        public virtual DbSet<Beskrivelsesvariabel> BeskrivelsesvariabelSet { get; set; }
        public virtual DbSet<Kriterie> KriterieSet { get; set; }
        public virtual DbSet<Påvirkning> PåvirkningSet { get; set; }
        public virtual DbSet<RødlisteVurdeingsenhetVersjon> RødlisteVurdeingsenhetVersjonSet { get; set; }
        public virtual DbSet<Naturnivå> NaturnivåSet { get; set; }
        public virtual DbSet<KodeVersjon> KodeVersjonSet { get; set; }
        public virtual DbSet<Naturområde_RødlisteKlassifisering> Naturområde_RødlisteKlassifiseringSet { get; set; }
    }
}
